export interface MenuItem {
  id: string
  name: string
  description: string | null
  price: number
  category: string
  available: boolean
  featured: boolean
  allergens: string[] | null
  image_url: string | null
  preparation_time: number | null
  ingredients: string[] | null
}

/**
 * Cardápio local do Armazém São Joaquim (CARDAPIO BR 2026).
 *
 * Usado como fallback quando a consulta ao Supabase falha ou não retorna itens,
 * para que a página /menu continue exibindo o cardápio completo.
 */
export const MENU_CATEGORIES = [
  'PETISCOS',
  'SALADAS',
  'PRATOS PRINCIPAIS',
  'VEGANO / VEGETARIANO',
  'SANDUÍCHES',
  'GUARNIÇÕES',
  'SOBREMESAS',
  'CAFÉS',
  'BEBIDAS SEM ÁLCOOL',
  'CERVEJAS',
  'COQUETÉIS',
  'CAIPIRINHAS',
  'DESTILADOS',
  'VINHOS',
] as const

export const FALLBACK_MENU_ITEMS: MenuItem[] = [
  {
    id: 'patatas-bravas',
    name: 'PATATAS BRAVAS',
    description: 'Batatas douradas com aioli de páprica levemente picante',
    price: 25.00,
    category: 'PETISCOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'pao-de-alho',
    name: 'PÃO DE ALHO',
    description: 'Porção aperitiva de pão de alho (02 un)',
    price: 12.00,
    category: 'PETISCOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/pao_de_alho.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'linguica-na-brasa',
    name: 'LINGUIÇA NA BRASA',
    description: 'Porção aperitiva de linguiça de churrasco, assada na parrilha e fatiada com cebola caramelizada (02 un)',
    price: 18.00,
    category: 'PETISCOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'torresmo',
    name: 'TORRESMO',
    description: 'Porção aperitiva frita, dourada (150g)',
    price: 18.00,
    category: 'PETISCOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/torresmo.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'pasteis-de-pupunha',
    name: 'PASTÉIS DE PUPUNHA',
    description: 'Porção aperitiva de pastel de palmito pupunha com leve toque de catupiry (06 un)',
    price: 42.00,
    category: 'PETISCOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'pasteis-de-queijo',
    name: 'PASTÉIS DE QUEIJO',
    description: 'Porção aperitiva de pastel de queijo (06 un)',
    price: 35.00,
    category: 'PETISCOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/pastel_de_queijo.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'pasteis-carne-seca-e-creme-de-queijo',
    name: 'PASTÉIS CARNE SECA E CREME DE QUEIJO',
    description: 'Porção aperitiva de pastel de carne seca com creme de queijo (06 un)',
    price: 42.00,
    category: 'PETISCOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/pasteis_carne_seca_e_creme_de_queijo.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'iscas-de-frango',
    name: 'ÍSCAS DE FRANGO',
    description: 'Porção aperitiva de frango empanada na farinha de Panko, frita e servida com molho aiole (≅120g de carne in natura)',
    price: 32.00,
    category: 'PETISCOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/iscas_de_frango.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'iscas-de-peixe',
    name: 'ÍSCAS DE PEIXE',
    description: 'Porção aperitiva de peixe empanada na farinha de Panko, frita e servida com molho aiole (≅120g de carne in natura)',
    price: 39.00,
    category: 'PETISCOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/iscas_de_peixe.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'atum-avocado',
    name: 'ATUM AVOCADO',
    description: 'Tartare de atum, temperado com teriyaki e mostarda sobre uma pasta de guacamole (avocado)',
    price: 58.00,
    category: 'PETISCOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'ceviche-carioca',
    name: 'CEVICHE CARIOCA',
    description: 'Tilápia marinada em suco de limão, gengibre, leite de coco, sal, cebola roxa, pimenta dedo de moça, coentro, milho peruano e chips de batata frita',
    price: 58.00,
    category: 'PETISCOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'vinagrete-de-polvo',
    name: 'VINAGRETE DE POLVO',
    description: 'Vinagrete, suco de limão, azeite, cebola, sal e pimenta, tomate e polvo fatiado com chips de banana da terra',
    price: 58.00,
    category: 'PETISCOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'palmito-pupunha',
    name: 'PALMITO PUPUNHA',
    description: 'Palmito assado na parrilha guarnecido com molho pesto',
    price: 39.00,
    category: 'PETISCOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/palmito_pupunha.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'linguica-artesanal-de-calabresa',
    name: 'LINGUIÇA ARTESANAL DE CALABRESA',
    description: 'Corte em fita da linguiça feita de carne de porco e temperos, pré-cozida e assada diretamente na parrilla, garantindo sabor defumado e textura macia. Servida com (02) pães de alho (500g)',
    price: 70.00,
    category: 'PETISCOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'lulinhas-do-armazem',
    name: 'LULINHAS DO ARMAZÉM',
    description: 'Anéis de lulinha empanados e temperados com vinho branco e ervas',
    price: 52.00,
    category: 'PETISCOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'bolinho-de-bacalhau',
    name: 'BOLINHO DE BACALHAU',
    description: 'Porção aperitiva de bolinho de bacalhau (06 un)',
    price: 32.00,
    category: 'PETISCOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/bolinho_de_bacalhau.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'croqueta-de-costela',
    name: 'CROQUETA DE COSTELA',
    description: 'Costela bovina cozida em baixa temperatura refogada com tempero da casa (04 un)',
    price: 45.00,
    category: 'PETISCOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/croqueta_de_costela.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'bolinho-de-feijoada',
    name: 'BOLINHO DE FEIJOADA',
    description: 'Bolinho de feijoada à moda da casa acompanhado com geleia de pimenta (04 un)',
    price: 42.00,
    category: 'PETISCOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/bolinho_de_feijoada.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'caprese-mineira',
    name: 'CAPRESE MINEIRA',
    description: 'Salada de tomate, queijo minas frescal, pesto de manjericão e torradas finas',
    price: 55.00,
    category: 'SALADAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/caprese_mineira.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'caesar-salad-com-fatias-de-frango',
    name: 'CAESAR SALAD COM FATIAS DE FRANGO',
    description: 'Alface americana, croutons e parmesão ralado, acompanha molho Caesar',
    price: 39.00,
    category: 'SALADAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/caesar_salad_com_frango.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'caesar-salad-sem-fatias-de-frango',
    name: 'CAESAR SALAD SEM FATIAS DE FRANGO',
    description: 'Alface americana, croutons e parmesão ralado, acompanha molho Caesar',
    price: 30.00,
    category: 'SALADAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/caesar_salad_sem_frango.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'salada-de-graos-com-tilapia',
    name: 'SALADA DE GRÃOS COM TILÁPIA',
    description: 'Tabule à base de grão com pepino, coentro, alface crespa e cenoura, servida com iscas de tilápia crocante',
    price: 58.00,
    category: 'SALADAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/salada_de_graos_com_tilapia.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'salada-de-graos-com-frango',
    name: 'SALADA DE GRÃOS COM FRANGO',
    description: 'Tabule à base de grão com pepino, coentro, alface crespa e cenoura, servida com iscas de frango à milanesa',
    price: 50.00,
    category: 'SALADAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/salada_de_graos_com_frango.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'bife-ancho',
    name: 'BIFE ANCHO',
    description: 'Carne — corte tradicional argentino, com molho chimichurri, acompanha legumes na brasa e batatas bravas (≅250g de carne in natura). Para 01 pessoa',
    price: 98.00,
    category: 'PRATOS PRINCIPAIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/bife_ancho.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'file-mignon-com-molho-de-cogumelos-e-polenta-cremosa',
    name: 'FILÉ MIGNON COM MOLHO DE COGUMELOS E POLENTA CREMOSA',
    description: 'Carne — medalhões de filé mignon, perfeitamente selados e suculentos, servidos sobre uma aveludada polenta cremosa de queijo parmesão. O prato é finalizado com um molho rústico e aromático de cogumelos frescos. Para 01 pessoa',
    price: 95.00,
    category: 'PRATOS PRINCIPAIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'pastel-de-choclo',
    name: 'PASTEL DE CHOCLO',
    description: 'Carne — prato típico do Chile. Camadas de carne moída temperada, azeitonas e ovos, cobertas por um cremoso purê de milho verde e manjericão, gratinado ao forno. Servido em cumbuca individual. Para 01 pessoa',
    price: 65.00,
    category: 'PRATOS PRINCIPAIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'chorizo-a-moda-da-casa-individual',
    name: 'CHORIZO À MODA DA CASA (INDIVIDUAL)',
    description: 'Carne — corte tradicional argentino de sabor intenso e maciez excepcional, acompanhado de alho confitado, batatas e cebolas grelhadas, farofa de ovo e chimichurri',
    price: 120.00,
    category: 'PRATOS PRINCIPAIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'picanha-ao-carvao',
    name: 'PICANHA AO CARVÃO',
    description: 'Carne — picanha assada na parrilla, com molho chimichurri, batatas bravas, farofa e vinagrete (≅500g de carne in natura). Para 02 pessoas',
    price: 195.00,
    category: 'PRATOS PRINCIPAIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/picanha_ao_carvao.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'mix-na-brasa',
    name: 'MIX NA BRASA',
    description: 'Carne — carne, linguiça (2), sobrecoxa, queijo coalho (2), pão de alho (2), vinagrete, farofa, patatas bravas e molho chimichurri. Para 02 pessoas',
    price: 150.00,
    category: 'PRATOS PRINCIPAIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/mix_na_brasa.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'bife-a-milanesa',
    name: 'BIFE À MILANESA',
    description: 'Carne — corte tradicional à milanesa envolvido por farinha panko e ovos batidos, purê de batata e acompanha legumes na brasa. Para 02 pessoas',
    price: 95.00,
    category: 'PRATOS PRINCIPAIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'chorizo-a-moda-da-casa-para-dois',
    name: 'CHORIZO À MODA DA CASA (PARA DOIS)',
    description: 'Carne — corte tradicional argentino de sabor intenso e maciez excepcional, acompanhado de alho confitado, batatas e cebolas grelhadas, farofa de ovo e chimichurri. Para 02 pessoas',
    price: 220.00,
    category: 'PRATOS PRINCIPAIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'feijoada-da-casa-individual',
    name: 'FEIJOADA DA CASA (INDIVIDUAL)',
    description: 'Culinária tradicional brasileira: feijoada típica, servida com farofa, arroz branco, carnes selecionadas, linguiça, torresmo, couve refogada e laranja fatiada, acompanhada de tigela de feijoada',
    price: 80.00,
    category: 'PRATOS PRINCIPAIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'feijoada-da-casa-para-dois',
    name: 'FEIJOADA DA CASA (PARA DOIS)',
    description: 'Culinária tradicional brasileira: feijoada típica, servida com farofa, arroz branco, carnes selecionadas, linguiça, torresmo, couve refogada e laranja fatiada, acompanhada de tigela de feijoada. Para 02 pessoas',
    price: 140.00,
    category: 'PRATOS PRINCIPAIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'buffet-de-feijoada-livre',
    name: 'BUFFET DE FEIJOADA LIVRE',
    description: 'Buffet de feijoada livre por pessoa, com farofa, arroz branco, carnes selecionadas, linguiça, torresmo, couve refogada e laranja fatiada',
    price: 110.00,
    category: 'PRATOS PRINCIPAIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'sobrecoxa-ao-carvao',
    name: 'SOBRECOXA AO CARVÃO',
    description: 'Frango — sobrecoxa assada na brasa com molho de mostarda, guarnecida de legumes grelhados na churrasqueira, farofa e vinagrete (≅300g de carne in natura). Para 01 pessoa',
    price: 70.00,
    category: 'PRATOS PRINCIPAIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'frango-com-arroz-basmati',
    name: 'FRANGO COM ARROZ BASMATI',
    description: 'Frango — sobrecoxa desossada assada e recheada, acompanha arroz basmati e ratatouille de legumes. Para 01 pessoa',
    price: 75.00,
    category: 'PRATOS PRINCIPAIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'frango-a-parmegiana',
    name: 'FRANGO A PARMEGIANA',
    description: 'Frango — filé de frango à milanesa, ao molho pomodoro e queijo gratinado, acompanha massa italiana. Para 01 pessoa',
    price: 80.00,
    category: 'PRATOS PRINCIPAIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'risoto-de-bacalhau',
    name: 'RISOTO DE BACALHAU',
    description: 'Peixes — risoto com lascas de bacalhau e tomate cereja frito, servido em cama de cebola caramelizada e azeitonas. Para 01 pessoa',
    price: 95.00,
    category: 'PRATOS PRINCIPAIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/risoto_de_bacalhau.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'tilapia-grelhada',
    name: 'TILÁPIA GRELHADA',
    description: 'Peixes — filé de tilápia grelhada com legumes e limão grelhados. Para 01 pessoa',
    price: 75.00,
    category: 'PRATOS PRINCIPAIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/tilapia_grelhada.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'dourado-a-moda-do-aipo',
    name: 'DOURADO À MODA DO AIPO',
    description: 'Peixes — filé de dourado grelhado com purê de aipo, acompanha crispy de alho poró. Para 01 pessoa',
    price: 85.00,
    category: 'PRATOS PRINCIPAIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'posta-de-salmao-grelhado',
    name: 'POSTA DE SALMÃO GRELHADO',
    description: 'Peixes — salmão grelhado com purê de batata, molho de maracujá, legumes e tomate cereja frito (≅170g de carne in natura). Para 01 pessoa',
    price: 90.00,
    category: 'PRATOS PRINCIPAIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/posta_de_salmao_grelhado.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'atum-em-crosta',
    name: 'ATUM EM CROSTA',
    description: 'Peixes — atum selado em crosta de gergelim, acompanhado de espaguete de legumes, molho à base de shoyu e tomate cereja frito (≅170g de carne in natura). Para 01 pessoa',
    price: 95.00,
    category: 'PRATOS PRINCIPAIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/atum_em_crosta.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'calamares-a-la-prancha',
    name: 'CALAMARES À LA PRANCHA',
    description: 'Peixes — calamares temperados com vinho branco e ervas, servidos com batatas bravas temperadas com páprica picante. Para 01 pessoa',
    price: 75.00,
    category: 'PRATOS PRINCIPAIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'polvo-grelhado-com-arroz-negro',
    name: 'POLVO GRELHADO COM ARROZ NEGRO',
    description: 'Peixes — polvo cozido temperado e grelhado na parrilha com arroz negro, tomate e limão assado na brasa. Para 01 pessoa',
    price: 130.00,
    category: 'PRATOS PRINCIPAIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/polvo_grelhado_com_arroz_negro.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'tilapia-na-brasa',
    name: 'TILÁPIA NA BRASA',
    description: 'Peixes — tilápia inteira assada na brasa e guarnecida de legumes (≅800g de carne in natura). Para 02 pessoas',
    price: 150.00,
    category: 'PRATOS PRINCIPAIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/tilapia_na_brasa.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'moqueca-banana-da-terra',
    name: 'MOQUECA BANANA DA TERRA',
    description: 'Moqueca de banana da terra com palmito e mix de pimentões, acompanhada de tomate cereja, arroz branco e farofa de dendê',
    price: 75.00,
    category: 'VEGANO / VEGETARIANO',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/moqueca_de_banana_da_terra.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'risoto-de-cogumelo',
    name: 'RISOTO DE COGUMELO',
    description: 'Delicioso e reconfortante risoto arbóreo, cozido "al dente". Combinação perfeita de cogumelos frescos salteados, finalizado com um toque de vinho branco, manteiga e parmesão cremoso',
    price: 90.00,
    category: 'VEGANO / VEGETARIANO',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'hamburguer-vegetariano',
    name: 'HAMBÚRGUER VEGETARIANO',
    description: 'Grão de bico com ervas, tomate confit, alface, cebola caramelizada e molho pesto, acompanhado de batatas rústicas',
    price: 60.00,
    category: 'VEGANO / VEGETARIANO',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'hamburguer-da-casa',
    name: 'HAMBÚRGUER DA CASA',
    description: 'Carne selecionada com queijo cheddar, cebola caramelizada, alface, tomate e batata da casa',
    price: 65.00,
    category: 'SANDUÍCHES',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/hamburguer_da_casa.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'chori-pao',
    name: 'CHORI-PÃO',
    description: 'Famoso choripan argentino na nossa versão carioca: pão baguete, linguiça de pernil e molho chimichurri',
    price: 35.00,
    category: 'SANDUÍCHES',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/chori_pao.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'paninni-de-carne',
    name: 'PANINNI DE CARNE',
    description: 'Pão ciabata com carne, tomate e molho pesto. Tostado na parrilha, acompanhado de batatas rústicas',
    price: 55.00,
    category: 'SANDUÍCHES',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'feijao',
    name: 'FEIJÃO',
    description: 'Porção de feijão',
    price: 15.00,
    category: 'GUARNIÇÕES',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/feijao.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'arroz',
    name: 'ARROZ',
    description: 'Porção de arroz',
    price: 14.00,
    category: 'GUARNIÇÕES',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/arroz.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'patatas-brava',
    name: 'PATATAS BRAVA',
    description: 'Porção de patatas bravas',
    price: 25.00,
    category: 'GUARNIÇÕES',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'legumes-na-brasa',
    name: 'LEGUMES NA BRASA',
    description: 'Porção de legumes na brasa',
    price: 15.00,
    category: 'GUARNIÇÕES',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'farofa',
    name: 'FAROFA',
    description: 'Porção de farofa',
    price: 10.00,
    category: 'GUARNIÇÕES',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'pure-de-batata',
    name: 'PURÊ DE BATATA',
    description: 'Porção de purê de batata',
    price: 15.00,
    category: 'GUARNIÇÕES',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'saladinha-da-casa',
    name: 'SALADINHA DA CASA',
    description: 'Porção de saladinha da casa',
    price: 15.00,
    category: 'GUARNIÇÕES',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/salada_da_casa.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'marquise-au-chocolat',
    name: 'MARQUISE AU CHOCOLAT',
    description: 'Saborosa sobremesa francesa clássica e requintada com ganache de chocolate meio amargo, sorvete de creme e coulis do dia',
    price: 28.00,
    category: 'SOBREMESAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'delicia-de-manga',
    name: 'DELÍCIA DE MANGA',
    description: 'Saborosa sobremesa brasileira feita de mousse de manga e coco, com molho de maracujá, decorada com fatias de manga e coco ralado',
    price: 28.00,
    category: 'SOBREMESAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/delicia_de_manga.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'tarte-aux-pommes',
    name: 'TARTE AUX POMMES',
    description: 'Deliciosa sobremesa francesa atemporal de massa sablée recheada com purê fino de maçã e lâminas de maçã, guarnecida de sorvete de creme e coulis do dia',
    price: 28.00,
    category: 'SOBREMESAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: '/images/menu_images/tarte_aux_pommes.webp',
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'espresso',
    name: 'ESPRESSO',
    description: 'Café espresso',
    price: 9.00,
    category: 'CAFÉS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'b43',
    name: 'B43',
    description: 'Licor 43, baileys, xarope de canela e espresso',
    price: 32.00,
    category: 'CAFÉS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'carajillo',
    name: 'CARAJILLO',
    description: 'Drink clássico à base de café espresso e licor',
    price: 32.00,
    category: 'CAFÉS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'agua-mineral-com-gas',
    name: 'ÁGUA MINERAL COM GÁS',
    description: 'Água mineral com gás',
    price: 9.00,
    category: 'BEBIDAS SEM ÁLCOOL',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'agua-mineral-sem-gas',
    name: 'ÁGUA MINERAL SEM GÁS',
    description: 'Água mineral sem gás',
    price: 9.00,
    category: 'BEBIDAS SEM ÁLCOOL',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'agua-de-coco',
    name: 'ÁGUA DE COCO',
    description: 'Água de coco (500ml)',
    price: 18.00,
    category: 'BEBIDAS SEM ÁLCOOL',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'agua-tonica',
    name: 'ÁGUA TÔNICA',
    description: 'Água tônica tradicional ou zero',
    price: 9.00,
    category: 'BEBIDAS SEM ÁLCOOL',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'shot-de-limao',
    name: 'SHOT DE LIMÃO',
    description: 'Shot de limão',
    price: 2.00,
    category: 'BEBIDAS SEM ÁLCOOL',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'refrigerante',
    name: 'REFRIGERANTE',
    description: 'Coca-Cola tradicional, Coca-Cola Zero, Guaraná tradicional ou Guaraná Zero',
    price: 9.00,
    category: 'BEBIDAS SEM ÁLCOOL',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'sodas-artesanais',
    name: 'SODAS ARTESANAIS',
    description: 'Hibisco, gengibre, capim-limão e maracujá',
    price: 14.00,
    category: 'BEBIDAS SEM ÁLCOOL',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'limonada',
    name: 'LIMONADA',
    description: 'Limonada suíça sem açúcar e coada',
    price: 14.00,
    category: 'BEBIDAS SEM ÁLCOOL',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'pink-lemonade',
    name: 'PINK LEMONADE',
    description: 'Limonada da casa, adoçada com xarope de hibisco',
    price: 14.00,
    category: 'BEBIDAS SEM ÁLCOOL',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'laranja-mix',
    name: 'LARANJA MIX',
    description: 'Suco de laranja pera e bahia',
    price: 14.00,
    category: 'BEBIDAS SEM ÁLCOOL',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'olha-o-mate',
    name: 'OLHA O MATE!',
    description: 'Mate adoçado com xarope artesanal. Opção: maracujá ou limão',
    price: 14.00,
    category: 'BEBIDAS SEM ÁLCOOL',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'red-bull-tropical',
    name: 'RED BULL TROPICAL',
    description: 'Energético Red Bull Tropical',
    price: 18.00,
    category: 'BEBIDAS SEM ÁLCOOL',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'red-bull-sugar-free',
    name: 'RED BULL SUGAR FREE',
    description: 'Energético Red Bull Sugar Free',
    price: 18.00,
    category: 'BEBIDAS SEM ÁLCOOL',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'red-bull-melancia',
    name: 'RED BULL MELANCIA',
    description: 'Energético Red Bull Melancia',
    price: 18.00,
    category: 'BEBIDAS SEM ÁLCOOL',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'amstel-600ml',
    name: 'AMSTEL 600ML',
    description: 'Cerveja Amstel (600ml)',
    price: 18.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'eisenbahn-600ml',
    name: 'EISENBAHN 600ML',
    description: 'Cerveja Eisenbahn (600ml)',
    price: 20.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'heineken-600ml',
    name: 'HEINEKEN 600ML',
    description: 'Cerveja Heineken (600ml)',
    price: 22.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'praya-600ml',
    name: 'PRAYA 600ML',
    description: 'Cerveja Praya (600ml)',
    price: 25.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'baden-baden-cristal-600ml',
    name: 'BADEN BADEN CRISTAL 600ML',
    description: 'Cerveja Baden Baden Cristal (600ml)',
    price: 28.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'baden-baden-golden-600ml',
    name: 'BADEN BADEN GOLDEN 600ML',
    description: 'Cerveja Baden Baden Golden (600ml)',
    price: 28.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'baden-baden-witbeer-600ml',
    name: 'BADEN BADEN WITBEER 600ML',
    description: 'Cerveja Baden Baden Witbeer (600ml)',
    price: 28.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'baden-baden-peach-600ml',
    name: 'BADEN BADEN PEACH 600ML',
    description: 'Cerveja Baden Baden Peach (600ml)',
    price: 28.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'baden-baden-american-ipa-600ml',
    name: 'BADEN BADEN AMERICAN IPA 600ML',
    description: 'Cerveja Baden Baden American IPA (600ml)',
    price: 28.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'praya-long-neck',
    name: 'PRAYA LONG NECK',
    description: 'Cerveja Praya (long neck)',
    price: 16.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'praya-sem-gluten-long-neck',
    name: 'PRAYA SEM GLÚTEN LONG NECK',
    description: 'Cerveja Praya sem glúten (long neck)',
    price: 16.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'amstel-long-neck',
    name: 'AMSTEL LONG NECK',
    description: 'Cerveja Amstel (long neck)',
    price: 12.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'eisenbahn-pilsen-long-neck',
    name: 'EISENBAHN PILSEN LONG NECK',
    description: 'Cerveja Eisenbahn Pilsen (long neck)',
    price: 15.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'eisenbahn-weiss-long-neck',
    name: 'EISENBAHN WEISS LONG NECK',
    description: 'Cerveja Eisenbahn Weiss (long neck)',
    price: 15.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'eisenbahn-ipa-long-neck',
    name: 'EISENBAHN IPA LONG NECK',
    description: 'Cerveja Eisenbahn IPA (long neck)',
    price: 15.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'heineken-long-neck',
    name: 'HEINEKEN LONG NECK',
    description: 'Cerveja Heineken (long neck)',
    price: 15.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'heineken-zero-long-neck',
    name: 'HEINEKEN ZERO LONG NECK',
    description: 'Cerveja Heineken Zero (long neck)',
    price: 15.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'sol-long-neck',
    name: 'SOL LONG NECK',
    description: 'Cerveja Sol, sem glúten (long neck)',
    price: 15.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'sol-zero-long-neck',
    name: 'SOL ZERO LONG NECK',
    description: 'Cerveja Sol Zero, sem glúten (long neck)',
    price: 15.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'lagunitas-long-neck',
    name: 'LAGUNITAS LONG NECK',
    description: 'Cerveja Lagunitas (long neck)',
    price: 25.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'blue-moon-long-neck',
    name: 'BLUE MOON LONG NECK',
    description: 'Cerveja Blue Moon (long neck)',
    price: 25.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'fazendinha-pilsen',
    name: 'FAZENDINHA PILSEN',
    description: 'Cerveja carioca do Complexo do Alemão (500ml)',
    price: 32.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'michelada',
    name: 'MICHELADA',
    description: 'Caneca com suco de tomate, molho inglês, suco de limão, Tabasco e sal na borda. Não inclusa a cerveja',
    price: 16.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'chelada',
    name: 'CHELADA',
    description: 'Caneca com suco de limão, Tabasco e sal na borda. Não inclusa a cerveja',
    price: 10.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'chopp-amstel',
    name: 'CHOPP AMSTEL',
    description: 'Chopp Amstel (350ml)',
    price: 13.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'chopp-heineken',
    name: 'CHOPP HEINEKEN',
    description: 'Chopp Heineken (350ml)',
    price: 15.00,
    category: 'CERVEJAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'cajueiro',
    name: 'CAJUEIRO',
    description: 'Cachaça Magnífica Cristal, caju, limão, açúcar, compota de caju e borda de castanha',
    price: 32.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'dilma-canta',
    name: 'DILMA CANTA',
    description: 'Cachaça Magnífica Tradicional Ipê, chá mate, polpa de maracujá, suco de abacaxi e xarope de coco',
    price: 32.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'rucula',
    name: 'RÚCULA',
    description: 'Cachaça Magnífica Cristal infusionada, folhas de rúcula, suco de limão siciliano e açúcar',
    price: 32.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'segredo-envelhecido',
    name: 'SEGREDO ENVELHECIDO',
    description: 'Cachaça Magnífica Extra Premium, cynar, bitter de cacau e xarope de caramelo salgado',
    price: 32.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'feitico-brasileiro',
    name: 'FEITIÇO BRASILEIRO',
    description: 'Cachaça Magnífica Extra Premium, chá mate, cynar, xarope de especiarias e suco de laranja',
    price: 32.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'o-mon-da-rafa',
    name: 'O MON DA RAFA',
    description: 'Vodka, jambuzada de banana, limão siciliano, folhas de hortelã e xarope simples',
    price: 32.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'amare-coffer',
    name: 'AMARE COFFER',
    description: 'Vodka, amareto, espresso e açúcar',
    price: 32.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'carioquissima',
    name: 'CARIOQUÍSSIMA',
    description: 'Vodka, limão siciliano, manjericão, açúcar e extrato de gengibre',
    price: 32.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'jambu-treme',
    name: 'JAMBU TREME',
    description: 'Jambuzada, caju, limão, gengibre e mel',
    price: 32.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'marajambu',
    name: 'MARAJAMBU',
    description: 'Jambuzada de abacaxi, maracujá, suco de laranja, xarope de melaço e suco de abacaxi',
    price: 32.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'helena',
    name: 'HELENA',
    description: 'Gin, morango, tangerina, limão taiti, açúcar, mel picante e tônica',
    price: 32.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'rubi-selvagem',
    name: 'RUBI SELVAGEM',
    description: 'Gin, chá de amora com framboesa, frutas vermelhas, suco de limão, xarope de hibisco e tônica',
    price: 32.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'doce-frescor',
    name: 'DOCE FRESCOR',
    description: 'Gin, manga, suco de laranja, suco de limão, xarope de maracujá e tônica',
    price: 32.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'doce-naufrago',
    name: 'DOCE NÁUFRAGO',
    description: 'Rum ouro, suco de abacaxi, amareto, suco de limão siciliano e xarope de melaço',
    price: 32.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'o-cacador-amargo',
    name: 'O CAÇADOR AMARGO',
    description: 'Rum prata, Jagermeister, fatias de hortelã, tangerina, suco de limão e açúcar',
    price: 32.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'pina-colada-do-armazem',
    name: 'PIÑA COLADA DO ARMAZÉM',
    description: 'Rum, leite condensado, abacaxi e xarope de coco',
    price: 32.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'pisco-do-sol',
    name: 'PISCO DO SOL',
    description: 'Pisco, suco de abacaxi, xarope de melaço e suco de limão',
    price: 32.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'aguas-de-marco',
    name: 'ÁGUAS DE MARÇO',
    description: 'Tequila prata, cupuaçu, xarope de coco e suco de limão',
    price: 32.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'a-paixao-do-mercado',
    name: 'A PAIXÃO DO MERCADO',
    description: 'Whiskey Jim Beam, polpa de maracujá, cachaça Gabrielinha, xarope de gengibre, suco de limão siciliano e xarope de canela',
    price: 32.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'cherry-cola',
    name: 'CHERRY COLA',
    description: 'Jim Beam Black Cherry, refrigerante de cola e limão',
    price: 32.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'jim-beam-mule',
    name: 'JIM BEAM MULE',
    description: 'Whiskey Jim Beam, xarope de gengibre, água com gás e suco de limão',
    price: 32.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'versao-sem-alcool',
    name: 'VERSÃO SEM ÁLCOOL',
    description: 'Consulte as versões sem álcool dos nossos coquetéis autorais',
    price: 28.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'classicos-standard',
    name: 'CLÁSSICOS — STANDARD',
    description: 'Clássicos que nunca saem de moda: Bloody Mary, Espresso Martini, Cosmopolitan, Moscow Mule, Mojito, Porn Star Martini, Boulevardier, Old Fashioned, Whiskey Sour, Manhattan, Gin Tônica, Rabo de Galo, Tequila Sunrise, Margarita, Daiquiri, Mimosa, Aperol Spritz, Basil Smash, Negroni, Dry Martini, Fitzgerald, Pisco Sour e Cuba Libre. Destilado standard',
    price: 38.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'classicos-premium',
    name: 'CLÁSSICOS — PREMIUM',
    description: 'Os mesmos clássicos da casa preparados com destilado premium',
    price: 42.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'classicos-super-premium',
    name: 'CLÁSSICOS — SUPER PREMIUM',
    description: 'Os mesmos clássicos da casa preparados com destilado super premium',
    price: 52.00,
    category: 'COQUETÉIS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'valentina',
    name: 'VALENTINA',
    description: 'Caipirinha exclusiva do Armazém: cachaça, tangerina, açúcar e gengibre. 300ml com cachaça prateada R$ 24 ou vodka R$ 26 | Caipirão 500ml com cachaça R$ 30 ou vodka R$ 35',
    price: 24.00,
    category: 'CAIPIRINHAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'da-pa-virada',
    name: 'DA PÁ VIRADA',
    description: 'Caipirinha exclusiva do Armazém: cachaça, mel, limão siciliano e limão taití. 300ml com cachaça prateada R$ 24 ou vodka R$ 26 | Caipirão 500ml com cachaça R$ 30 ou vodka R$ 35',
    price: 24.00,
    category: 'CAIPIRINHAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'goro',
    name: 'GORÓ',
    description: 'Caipirinha exclusiva do Armazém: cachaça, maracujá e xarope de especiarias. 300ml com cachaça prateada R$ 24 ou vodka R$ 26 | Caipirão 500ml com cachaça R$ 30 ou vodka R$ 35',
    price: 24.00,
    category: 'CAIPIRINHAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'leve-e-solta',
    name: 'LEVE E SOLTA',
    description: 'Caipirinha exclusiva do Armazém: cachaça, abacaxi, melaço e limão taití. 300ml com cachaça prateada R$ 24 ou vodka R$ 26 | Caipirão 500ml com cachaça R$ 30 ou vodka R$ 35',
    price: 24.00,
    category: 'CAIPIRINHAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'caipirinha-magnifica',
    name: 'CAIPIRINHA MAGNÍFICA',
    description: 'Versões exclusivas (Valentina, Da Pá Virada, Goró ou Leve e Solta) feitas com cachaça Magnífica. 300ml R$ 26 | Caipirão 450ml R$ 32',
    price: 26.00,
    category: 'CAIPIRINHAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'trio-caipira-magnifica',
    name: 'TRIO CAIPIRA MAGNÍFICA',
    description: 'Clássico trio degustação com os sabores mais pedidos da casa em copos de 200ml: Dois Irmãos (cachaça cristal, limão taití, limão siciliano e xarope de especiarias), São Joaquim (cachaça bica do alambique, abacaxi e xarope de mel) e Vem Cá Minha Flor (cachaça tradicional ipê, maracujá, manjericão e xarope de baunilha)',
    price: 38.00,
    category: 'CAIPIRINHAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'caipirinha-de-limao',
    name: 'CAIPIRINHA DE LIMÃO',
    description: 'Caipirinha tradicional de limão (300ml). Feita com cachaça prateada R$ 22, vodka R$ 24 ou saquê R$ 24',
    price: 22.00,
    category: 'CAIPIRINHAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'frutas-da-estacao',
    name: 'FRUTAS DA ESTAÇÃO',
    description: 'Caipirinha tradicional com a fruta do dia (300ml). Feita com cachaça prateada, vodka ou saquê. Consulte a disponibilidade da fruta do dia',
    price: 26.00,
    category: 'CAIPIRINHAS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'cachaca-prateada',
    name: 'CACHAÇA PRATEADA',
    description: 'Cachaça — dose',
    price: 12.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'jambuzada-abacaxi',
    name: 'JAMBUZADA ABACAXI',
    description: 'Cachaça — dose',
    price: 18.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'jambuzada-banana',
    name: 'JAMBUZADA BANANA',
    description: 'Cachaça — dose',
    price: 18.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'jambuzada-tradicional',
    name: 'JAMBUZADA TRADICIONAL',
    description: 'Cachaça — dose',
    price: 18.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'magnifica-cristal',
    name: 'MAGNÍFICA CRISTAL',
    description: 'Cachaça — dose',
    price: 15.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'magnifica-bica-do-alambique',
    name: 'MAGNÍFICA BICA DO ALAMBIQUE',
    description: 'Cachaça — dose',
    price: 18.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'magnifica-tradicional-ipe',
    name: 'MAGNÍFICA TRADICIONAL IPÊ',
    description: 'Cachaça — dose',
    price: 20.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'magnifica-extra-premium',
    name: 'MAGNÍFICA EXTRA PREMIUM',
    description: 'Cachaça — dose',
    price: 24.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'magnifica-soleira',
    name: 'MAGNÍFICA SOLEIRA',
    description: 'Cachaça — dose',
    price: 55.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'jim-beam',
    name: 'JIM BEAM',
    description: 'Whiskey — dose',
    price: 25.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'jim-beam-black-cherry',
    name: 'JIM BEAM BLACK CHERRY',
    description: 'Whiskey — dose',
    price: 28.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'jim-beam-honey',
    name: 'JIM BEAM HONEY',
    description: 'Whiskey — dose',
    price: 25.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'jim-beam-black',
    name: 'JIM BEAM BLACK',
    description: 'Whiskey — dose',
    price: 35.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'jim-beam-rye',
    name: 'JIM BEAM RYE',
    description: 'Whiskey — dose',
    price: 30.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'maker-s-mark',
    name: 'MAKER\'S MARK',
    description: 'Whiskey — dose',
    price: 45.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'jack-daniel-s',
    name: 'JACK DANIEL\'S',
    description: 'Whiskey — dose',
    price: 32.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'jack-daniel-s-honey',
    name: 'JACK DANIEL\'S HONEY',
    description: 'Whiskey — dose',
    price: 30.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'jameson',
    name: 'JAMESON',
    description: 'Whiskey — dose',
    price: 28.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'chivas-12',
    name: 'CHIVAS 12',
    description: 'Whiskey — dose',
    price: 32.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'bulleit',
    name: 'BULLEIT',
    description: 'Whiskey — dose',
    price: 54.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'bombay-sapphire',
    name: 'BOMBAY SAPPHIRE',
    description: 'Gin — dose',
    price: 28.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'tanqueray',
    name: 'TANQUERAY',
    description: 'Gin — dose',
    price: 30.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'beefeater',
    name: 'BEEFEATER',
    description: 'Gin — dose',
    price: 28.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'hendrick-s',
    name: 'HENDRICK\'S',
    description: 'Gin — dose',
    price: 48.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'roku',
    name: 'ROKU',
    description: 'Gin — dose',
    price: 40.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'tanqueray-ten',
    name: 'TANQUERAY TEN',
    description: 'Gin — dose',
    price: 45.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'absolut',
    name: 'ABSOLUT',
    description: 'Vodka — dose',
    price: 20.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'haku',
    name: 'HAKU',
    description: 'Vodka — dose',
    price: 42.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'ketel-one',
    name: 'KETEL ONE',
    description: 'Vodka — dose',
    price: 28.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'grey-goose',
    name: 'GREY GOOSE',
    description: 'Vodka — dose',
    price: 34.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'absolut-citron',
    name: 'ABSOLUT CITRON',
    description: 'Vodka — dose',
    price: 24.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'bacardi-anejo-4',
    name: 'BACARDI AÑEJO 4',
    description: 'Rum — dose',
    price: 20.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'bacardi-reserva-ocho',
    name: 'BACARDI RESERVA OCHO',
    description: 'Rum — dose',
    price: 30.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'havana-club-3-anos',
    name: 'HAVANA CLUB 3 AÑOS',
    description: 'Rum — dose',
    price: 26.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'havana-club-7-anos',
    name: 'HAVANA CLUB 7 AÑOS',
    description: 'Rum — dose',
    price: 30.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'jose-cuervo-prata',
    name: 'JOSE CUERVO PRATA',
    description: 'Tequila — dose',
    price: 30.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'jose-cuervo-ouro',
    name: 'JOSE CUERVO OURO',
    description: 'Tequila — dose',
    price: 35.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'jagermeister',
    name: 'JAGERMEISTER',
    description: 'Licor — dose',
    price: 40.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'licor-43',
    name: 'LICOR 43',
    description: 'Licor — dose',
    price: 35.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'campari',
    name: 'CAMPARI',
    description: 'Licor — dose',
    price: 18.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'fernet-branca',
    name: 'FERNET BRANCA',
    description: 'Licor — dose',
    price: 29.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'baileys',
    name: 'BAILEYS',
    description: 'Licor — dose',
    price: 32.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'amarula',
    name: 'AMARULA',
    description: 'Licor — dose',
    price: 28.00,
    category: 'DESTILADOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'chamarmuyo-estate-malbec',
    name: 'CHAMARMUYO ESTATE MALBEC',
    description: 'Vinho tinto — Malbec, Argentina',
    price: 130.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'cordero-en-piel-de-lobo-tinto',
    name: 'CORDERO EN PIEL DE LOBO (TINTO)',
    description: 'Vinho tinto — Malbec, Argentina, 2022',
    price: 110.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'cuesta-del-madero-tinto',
    name: 'CUESTA DEL MADERO (TINTO)',
    description: 'Vinho tinto — Bonarda Malbec, Argentina, 2022',
    price: 95.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'finca-la-linda-tinto',
    name: 'FINCA LA LINDA (TINTO)',
    description: 'Vinho tinto — Malbec, Argentina, 2025',
    price: 130.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'flores-negras',
    name: 'FLORES NEGRAS',
    description: 'Vinho tinto — Cabernet Franc, Argentina',
    price: 140.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'luigi-bosca',
    name: 'LUIGI BOSCA',
    description: 'Vinho tinto — Malbec, Argentina, 2024',
    price: 260.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'minimalista-red-blend',
    name: 'MINIMALISTA RED BLEND',
    description: 'Vinho tinto — Red Blend, Argentina, 2020',
    price: 95.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'morande-single-vineyard',
    name: 'MORANDÉ SINGLE VINEYARD',
    description: 'Vinho tinto — Pinot Noir, Chile, 2022',
    price: 150.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'zorzal-terroir-unico-tinto',
    name: 'ZORZAL TERROIR ÚNICO (TINTO)',
    description: 'Vinho tinto — Malbec, Argentina, 2024',
    price: 150.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'abras-malbec',
    name: 'ABRAS MALBEC',
    description: 'Vinho tinto — Malbec, Argentina, 2023',
    price: 220.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'amalaya-tinto',
    name: 'AMALAYA (TINTO)',
    description: 'Vinho tinto — Gran Corte Tinto Malbec, Argentina',
    price: 160.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'enrique-foster-ique',
    name: 'ENRIQUE FOSTER IQUE',
    description: 'Vinho tinto — Cabernet Sauvignon, Argentina, 2023',
    price: 100.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'cordero-en-piel-de-lobo-branco',
    name: 'CORDERO EN PIEL DE LOBO (BRANCO)',
    description: 'Vinho branco — Blend de blancas, Argentina, 2022',
    price: 110.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'cuesta-del-madero-branco',
    name: 'CUESTA DEL MADERO (BRANCO)',
    description: 'Vinho branco — Reserva Orgânico Chardonnay Chenin, Argentina, 2022',
    price: 95.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'finca-la-linda-branco',
    name: 'FINCA LA LINDA (BRANCO)',
    description: 'Vinho branco — Chardonnay, Argentina, 2025',
    price: 130.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'pacheco-pereda',
    name: 'PACHECO PEREDA',
    description: 'Vinho branco — Chardonnay, Argentina',
    price: 100.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'zorzal-terroir-unico-branco',
    name: 'ZORZAL TERROIR ÚNICO (BRANCO)',
    description: 'Vinho branco — Sauvignon Blanc, Argentina, 2024',
    price: 150.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'minimalista-branco',
    name: 'MINIMALISTA BRANCO',
    description: 'Vinho branco — Pinot Grigio, Argentina, 2023',
    price: 95.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'morande-branco',
    name: 'MORANDÉ BRANCO',
    description: 'Vinho branco — Gewürztraminer, Chile, 2023',
    price: 180.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'latitude',
    name: 'LATITUDE',
    description: 'Vinho branco — Sauvignon Blanc, Chile',
    price: 90.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'cordero-en-piel-de-lobo-rose',
    name: 'CORDERO EN PIEL DE LOBO (ROSÉ)',
    description: 'Vinho rosé — Malbec rosé, Argentina, 2023',
    price: 110.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'viumanet-rose',
    name: 'VIUMANET ROSE',
    description: 'Vinho rosé — Malbec rosé, Chile',
    price: 125.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'perez-cruz-lingal',
    name: 'PEREZ CRUZ LINGAL',
    description: 'Vinho rosé — Grenache Mouvedre, Argentina',
    price: 140.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'minimalista-rose',
    name: 'MINIMALISTA ROSE',
    description: 'Vinho rosé — Mendoza, Argentina, 2023',
    price: 95.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'zorzal-terroir-unico-rose',
    name: 'ZORZAL TERROIR ÚNICO (ROSÉ)',
    description: 'Vinho rosé — Pinot Noir rosé, Argentina, 2024',
    price: 150.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'amalaya-rose',
    name: 'AMALAYA (ROSÉ)',
    description: 'Vinho rosé — Blend Malbec, Argentina',
    price: 140.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'chandon-reserve-brut',
    name: 'CHANDON RÉSERVE BRUT',
    description: 'Espumante — Chandon Réserve Brut',
    price: 180.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'cava-ophicus-branco',
    name: 'CAVA OPHICUS BRANCO',
    description: 'Espumante — Cava Ophicus Branco',
    price: 120.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'cava-ophicus-rose',
    name: 'CAVA OPHICUS ROSÉ',
    description: 'Espumante — Cava Ophicus Rosé',
    price: 120.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
  {
    id: 'taca-de-vinho',
    name: 'TAÇA DE VINHO',
    description: 'Taça de vinho (01 unidade). Consulte sobre os rótulos disponíveis',
    price: 28.00,
    category: 'VINHOS',
    available: true,
    featured: false,
    allergens: null,
    image_url: null,
    preparation_time: null,
    ingredients: null,
  },
]
